### ISSUE TITLE
Craft email messaging and visual materials for each category of school we are reaching out to

### ISSUE THREAD

**Issue by lexieabrahamian** [promazo/100K-Mentors-PR-Students#17]
This could be a template with the actual words we want to use, but it will be helpful to change each email slightly depending on the receiving department so it makes sense and seems intentional. All email messaging should include a request to set up a meeting over video call. 

-Determine what our _asks_ are for both kinds of institutions, perhaps even based on the specific department we are reaching out to (if they have a unique audience). We could have different types of asks as we will not be able to talk with every university target because of timing in which case we would want to have materials that they can send throughout the University. As we get going we may want to ask for advice on how we can spread this opportunity to students across their campuses. In that meeting, we could have them connect us to other people they may know at other Universities.

- Craft email email messaging for HBCUs

- Craft email messaging for state colleges and universities

-Each email template should include a custom 1:1 section to personalize emails without having to re-write each person/recipient's email.  

- Work with Adam and other ProMazo staff to create or locate marketing graphics to send in the email for these departments to use if they are going to be advertising on any kind of online opportunity board.

**Done** = 2-3 email templates for the different kinds of institutions with the intended marketing graphics included. Set up a time to review with Adam and the student intern team.

**Comment by aflies1** [comment]
I like this. For reaching out through email we will need to think through what our ask is. We could have different types of asks as we will not be able to talk with every university target because of timing in which case we would want to have materials that they can send throughout the University. As we get going we may want to ask for advice on how we can spread this opportunity to students across their campuses. In that meeting, we could have them connect us to other people they may know at other Universities.

**Comment by lexieabrahamian** [comment]
2-3 email asks/templates
